# Generated by Django 2.2.1 on 2019-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
