# Generated by Django 2.2.1 on 2019-06-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190608_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='picture',
        ),
    ]
